title: I am a title
author: Myself
email: blabla@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a description

# social links
twitter_username: I-do-not-have-twitter # DO NOT include the @ character, or else the build will fail!
github_username:  I-am-a-username # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
